<?php
$albums=$this->albums;
$form = $this->form;
$form->prepare();
?>

<h1>Загрузка фотографии</h1>

<p>
    Пожалуйста, заполните следующую форму и нажмите кнопку <i>Upload</i>.
</p>

<?php if(!isset($albums)): ?>
    <p>Внимание, перед добавлением фотографий нужно создать альбом</p>
    <br>
    <a href="<?=$this->url('albums/create') ?>">Добавить альбом</a>
<? else:?>

<div>
    <div>
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <!--Выбор альбома -->
            <label>Выберите альбом : </label>
            <select name="idAlbum">
                <?php foreach ($albums as $album): ?>
                    <option value="<?= $album->getId() ?>">
                        <?= '# '.$album->getId().' -  '.$album->getLabel() ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <br>
            <!--заголовок фотографии-->
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
            <br>
            <!--адрес съемки фотографии-->
            <?= $this->formLabel($form->get('geo')); ?>
            <?= $this->formElement($form->get('geo')); ?>
            <?= $this->formElementErrors($form->get('geo')); ?>
            <br>
            <!--выбор файла для загрузки фотографии-->
            <?= $this->formLabel($form->get('file')); ?>
            <?= $this->formElement($form->get('file')); ?>
            <?= $this->formElementErrors($form->get('file')); ?>
            <br>
            <!--<div class="hint">(PNG and JPG formats are allowed)</div>-->
        </div>
        <!-- кнопка-->
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<?php endif;?>